//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.04 at 06:31:51 PM EDT 
//


package com.slice.datatypes.fileconfiguration;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MessagesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MessagesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="PageTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TopTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ContentTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ContentDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TextToSearchFor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SpecifyExclude" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SpecifyOnlyInclude" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MessagesType", propOrder = {

})
public class MessagesDTO {

    @XmlElement(name = "PageTitle", required = true)
    protected String pageTitle;
    @XmlElement(name = "TopTitle", required = true)
    protected String topTitle;
    @XmlElement(name = "ContentTitle", required = true)
    protected String contentTitle;
    @XmlElement(name = "ContentDescription", required = true)
    protected String contentDescription;
    @XmlElement(name = "TextToSearchFor", required = true)
    protected String textToSearchFor;
    @XmlElement(name = "SpecifyExclude", required = true)
    protected String specifyExclude;
    @XmlElement(name = "SpecifyOnlyInclude", required = true)
    protected String specifyOnlyInclude;

    /**
     * Gets the value of the pageTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPageTitle() {
        return pageTitle;
    }

    /**
     * Sets the value of the pageTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPageTitle(String value) {
        this.pageTitle = value;
    }

    /**
     * Gets the value of the topTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTopTitle() {
        return topTitle;
    }

    /**
     * Sets the value of the topTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTopTitle(String value) {
        this.topTitle = value;
    }

    /**
     * Gets the value of the contentTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentTitle() {
        return contentTitle;
    }

    /**
     * Sets the value of the contentTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentTitle(String value) {
        this.contentTitle = value;
    }

    /**
     * Gets the value of the contentDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentDescription() {
        return contentDescription;
    }

    /**
     * Sets the value of the contentDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentDescription(String value) {
        this.contentDescription = value;
    }

    /**
     * Gets the value of the textToSearchFor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextToSearchFor() {
        return textToSearchFor;
    }

    /**
     * Sets the value of the textToSearchFor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextToSearchFor(String value) {
        this.textToSearchFor = value;
    }

    /**
     * Gets the value of the specifyExclude property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecifyExclude() {
        return specifyExclude;
    }

    /**
     * Sets the value of the specifyExclude property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecifyExclude(String value) {
        this.specifyExclude = value;
    }

    /**
     * Gets the value of the specifyOnlyInclude property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecifyOnlyInclude() {
        return specifyOnlyInclude;
    }

    /**
     * Sets the value of the specifyOnlyInclude property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecifyOnlyInclude(String value) {
        this.specifyOnlyInclude = value;
    }

}
