//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.04 at 06:31:51 PM EDT 
//


package com.slice.datatypes.fileconfiguration;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.slice.datatypes.fileconfiguration package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Config_QNAME = new QName("http://www.slice.com/datatypes/FileConfiguration", "Config");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.slice.datatypes.fileconfiguration
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ComponentsDTO }
     * 
     */
    public ComponentsDTO createComponentsDTO() {
        return new ComponentsDTO();
    }

    /**
     * Create an instance of {@link ProductDTO }
     * 
     */
    public ProductDTO createProductDTO() {
        return new ProductDTO();
    }

    /**
     * Create an instance of {@link ProductDTO.SearchIndex }
     * 
     */
    public ProductDTO.SearchIndex createProductDTOSearchIndex() {
        return new ProductDTO.SearchIndex();
    }

    /**
     * Create an instance of {@link ConfigDTO }
     * 
     */
    public ConfigDTO createConfigDTO() {
        return new ConfigDTO();
    }

    /**
     * Create an instance of {@link ConfigEntriesDTO }
     * 
     */
    public ConfigEntriesDTO createConfigEntriesDTO() {
        return new ConfigEntriesDTO();
    }

    /**
     * Create an instance of {@link SearchFileTypesDTO }
     * 
     */
    public SearchFileTypesDTO createSearchFileTypesDTO() {
        return new SearchFileTypesDTO();
    }

    /**
     * Create an instance of {@link SearchFileTypeDTO }
     * 
     */
    public SearchFileTypeDTO createSearchFileTypeDTO() {
        return new SearchFileTypeDTO();
    }

    /**
     * Create an instance of {@link IndexerIgnoreListTypeDTO }
     * 
     */
    public IndexerIgnoreListTypeDTO createIndexerIgnoreListTypeDTO() {
        return new IndexerIgnoreListTypeDTO();
    }

    /**
     * Create an instance of {@link MessagesDTO }
     * 
     */
    public MessagesDTO createMessagesDTO() {
        return new MessagesDTO();
    }

    /**
     * Create an instance of {@link ComponentsDTO.Component }
     * 
     */
    public ComponentsDTO.Component createComponentsDTOComponent() {
        return new ComponentsDTO.Component();
    }

    /**
     * Create an instance of {@link ProductDTO.AllowList }
     * 
     */
    public ProductDTO.AllowList createProductDTOAllowList() {
        return new ProductDTO.AllowList();
    }

    /**
     * Create an instance of {@link ProductDTO.SearchIndex.JavaSrc }
     * 
     */
    public ProductDTO.SearchIndex.JavaSrc createProductDTOSearchIndexJavaSrc() {
        return new ProductDTO.SearchIndex.JavaSrc();
    }

    /**
     * Create an instance of {@link ProductDTO.SearchIndex.Lucene }
     * 
     */
    public ProductDTO.SearchIndex.Lucene createProductDTOSearchIndexLucene() {
        return new ProductDTO.SearchIndex.Lucene();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConfigDTO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.slice.com/datatypes/FileConfiguration", name = "Config")
    public JAXBElement<ConfigDTO> createConfig(ConfigDTO value) {
        return new JAXBElement<ConfigDTO>(_Config_QNAME, ConfigDTO.class, null, value);
    }

}
