//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.12 at 02:38:03 PM EST 
//


package com.slice.datatypes.fileconfiguration;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProductType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProductType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PathToSourceDir" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SearchWhoaCowboyFilesNumberText" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SearchWhoaCowboyFilesNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="SearchWhoaCowboyQueryTimeoutInSecs" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="SearchComponentMapFile" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LogFileOutPath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SearchAdminEmail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CookieName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Messages" type="{http://www.slice.com/datatypes/FileConfiguration}MessagesType"/>
 *         &lt;element name="Components" type="{http://www.slice.com/datatypes/FileConfiguration}ComponentsType" minOccurs="0"/>
 *         &lt;element name="AllowList" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Allow" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SearchIndex">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="JavaSrc">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="JavaSrcFsDatabasePath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="JavaSrcFsDatabaseUrl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Lucene">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="JavaSrcFsLuceneDatabasePath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="IndexerIgnoreList" type="{http://www.slice.com/datatypes/FileConfiguration}IndexerIgnoreListType" minOccurs="0"/>
 *         &lt;element name="SearchFileTypes" type="{http://www.slice.com/datatypes/FileConfiguration}SearchFileTypes"/>
 *         &lt;element name="FileIndexerPath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DatabasePresharedKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProductType", propOrder = {

})
public class ProductDTO {

    @XmlElement(name = "Id", required = true)
    protected String id;
    @XmlElement(name = "PathToSourceDir", required = true)
    protected String pathToSourceDir;
    @XmlElement(name = "SearchWhoaCowboyFilesNumberText", required = true)
    protected String searchWhoaCowboyFilesNumberText;
    @XmlElement(name = "SearchWhoaCowboyFilesNumber")
    protected int searchWhoaCowboyFilesNumber;
    @XmlElement(name = "SearchWhoaCowboyQueryTimeoutInSecs")
    protected int searchWhoaCowboyQueryTimeoutInSecs;
    @XmlElement(name = "SearchComponentMapFile")
    protected String searchComponentMapFile;
    @XmlElement(name = "LogFileOutPath")
    protected String logFileOutPath;
    @XmlElement(name = "SearchAdminEmail", required = true)
    protected String searchAdminEmail;
    @XmlElement(name = "CookieName", required = true)
    protected String cookieName;
    @XmlElement(name = "Messages", required = true)
    protected MessagesDTO messages;
    @XmlElement(name = "Components")
    protected ComponentsDTO components;
    @XmlElement(name = "AllowList")
    protected ProductDTO.AllowList allowList;
    @XmlElement(name = "SearchIndex", required = true)
    protected ProductDTO.SearchIndex searchIndex;
    @XmlElement(name = "IndexerIgnoreList")
    protected IndexerIgnoreListTypeDTO indexerIgnoreList;
    @XmlElement(name = "SearchFileTypes", required = true)
    protected SearchFileTypesDTO searchFileTypes;
    @XmlElement(name = "FileIndexerPath")
    protected String fileIndexerPath;
    @XmlElement(name = "DatabasePresharedKey")
    protected String databasePresharedKey;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the pathToSourceDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPathToSourceDir() {
        return pathToSourceDir;
    }

    /**
     * Sets the value of the pathToSourceDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPathToSourceDir(String value) {
        this.pathToSourceDir = value;
    }

    /**
     * Gets the value of the searchWhoaCowboyFilesNumberText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchWhoaCowboyFilesNumberText() {
        return searchWhoaCowboyFilesNumberText;
    }

    /**
     * Sets the value of the searchWhoaCowboyFilesNumberText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchWhoaCowboyFilesNumberText(String value) {
        this.searchWhoaCowboyFilesNumberText = value;
    }

    /**
     * Gets the value of the searchWhoaCowboyFilesNumber property.
     * 
     */
    public int getSearchWhoaCowboyFilesNumber() {
        return searchWhoaCowboyFilesNumber;
    }

    /**
     * Sets the value of the searchWhoaCowboyFilesNumber property.
     * 
     */
    public void setSearchWhoaCowboyFilesNumber(int value) {
        this.searchWhoaCowboyFilesNumber = value;
    }

    /**
     * Gets the value of the searchWhoaCowboyQueryTimeoutInSecs property.
     * 
     */
    public int getSearchWhoaCowboyQueryTimeoutInSecs() {
        return searchWhoaCowboyQueryTimeoutInSecs;
    }

    /**
     * Sets the value of the searchWhoaCowboyQueryTimeoutInSecs property.
     * 
     */
    public void setSearchWhoaCowboyQueryTimeoutInSecs(int value) {
        this.searchWhoaCowboyQueryTimeoutInSecs = value;
    }

    /**
     * Gets the value of the searchComponentMapFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchComponentMapFile() {
        return searchComponentMapFile;
    }

    /**
     * Sets the value of the searchComponentMapFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchComponentMapFile(String value) {
        this.searchComponentMapFile = value;
    }

    /**
     * Gets the value of the logFileOutPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogFileOutPath() {
        return logFileOutPath;
    }

    /**
     * Sets the value of the logFileOutPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogFileOutPath(String value) {
        this.logFileOutPath = value;
    }

    /**
     * Gets the value of the searchAdminEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchAdminEmail() {
        return searchAdminEmail;
    }

    /**
     * Sets the value of the searchAdminEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchAdminEmail(String value) {
        this.searchAdminEmail = value;
    }

    /**
     * Gets the value of the cookieName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCookieName() {
        return cookieName;
    }

    /**
     * Sets the value of the cookieName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCookieName(String value) {
        this.cookieName = value;
    }

    /**
     * Gets the value of the messages property.
     * 
     * @return
     *     possible object is
     *     {@link MessagesDTO }
     *     
     */
    public MessagesDTO getMessages() {
        return messages;
    }

    /**
     * Sets the value of the messages property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessagesDTO }
     *     
     */
    public void setMessages(MessagesDTO value) {
        this.messages = value;
    }

    /**
     * Gets the value of the components property.
     * 
     * @return
     *     possible object is
     *     {@link ComponentsDTO }
     *     
     */
    public ComponentsDTO getComponents() {
        return components;
    }

    /**
     * Sets the value of the components property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComponentsDTO }
     *     
     */
    public void setComponents(ComponentsDTO value) {
        this.components = value;
    }

    /**
     * Gets the value of the allowList property.
     * 
     * @return
     *     possible object is
     *     {@link ProductDTO.AllowList }
     *     
     */
    public ProductDTO.AllowList getAllowList() {
        return allowList;
    }

    /**
     * Sets the value of the allowList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductDTO.AllowList }
     *     
     */
    public void setAllowList(ProductDTO.AllowList value) {
        this.allowList = value;
    }

    /**
     * Gets the value of the searchIndex property.
     * 
     * @return
     *     possible object is
     *     {@link ProductDTO.SearchIndex }
     *     
     */
    public ProductDTO.SearchIndex getSearchIndex() {
        return searchIndex;
    }

    /**
     * Sets the value of the searchIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductDTO.SearchIndex }
     *     
     */
    public void setSearchIndex(ProductDTO.SearchIndex value) {
        this.searchIndex = value;
    }

    /**
     * Gets the value of the indexerIgnoreList property.
     * 
     * @return
     *     possible object is
     *     {@link IndexerIgnoreListTypeDTO }
     *     
     */
    public IndexerIgnoreListTypeDTO getIndexerIgnoreList() {
        return indexerIgnoreList;
    }

    /**
     * Sets the value of the indexerIgnoreList property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndexerIgnoreListTypeDTO }
     *     
     */
    public void setIndexerIgnoreList(IndexerIgnoreListTypeDTO value) {
        this.indexerIgnoreList = value;
    }

    /**
     * Gets the value of the searchFileTypes property.
     * 
     * @return
     *     possible object is
     *     {@link SearchFileTypesDTO }
     *     
     */
    public SearchFileTypesDTO getSearchFileTypes() {
        return searchFileTypes;
    }

    /**
     * Sets the value of the searchFileTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchFileTypesDTO }
     *     
     */
    public void setSearchFileTypes(SearchFileTypesDTO value) {
        this.searchFileTypes = value;
    }

    /**
     * Gets the value of the fileIndexerPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileIndexerPath() {
        return fileIndexerPath;
    }

    /**
     * Sets the value of the fileIndexerPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileIndexerPath(String value) {
        this.fileIndexerPath = value;
    }

    /**
     * Gets the value of the databasePresharedKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatabasePresharedKey() {
        return databasePresharedKey;
    }

    /**
     * Sets the value of the databasePresharedKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatabasePresharedKey(String value) {
        this.databasePresharedKey = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Allow" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "allow"
    })
    public static class AllowList {

        @XmlElement(name = "Allow", required = true)
        protected List<String> allow;

        /**
         * Gets the value of the allow property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the allow property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAllow().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getAllow() {
            if (allow == null) {
                allow = new ArrayList<String>();
            }
            return this.allow;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="JavaSrc">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="JavaSrcFsDatabasePath" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="JavaSrcFsDatabaseUrl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Lucene">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="JavaSrcFsLuceneDatabasePath" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "javaSrc",
        "lucene"
    })
    public static class SearchIndex {

        @XmlElement(name = "JavaSrc")
        protected ProductDTO.SearchIndex.JavaSrc javaSrc;
        @XmlElement(name = "Lucene")
        protected ProductDTO.SearchIndex.Lucene lucene;

        /**
         * Gets the value of the javaSrc property.
         * 
         * @return
         *     possible object is
         *     {@link ProductDTO.SearchIndex.JavaSrc }
         *     
         */
        public ProductDTO.SearchIndex.JavaSrc getJavaSrc() {
            return javaSrc;
        }

        /**
         * Sets the value of the javaSrc property.
         * 
         * @param value
         *     allowed object is
         *     {@link ProductDTO.SearchIndex.JavaSrc }
         *     
         */
        public void setJavaSrc(ProductDTO.SearchIndex.JavaSrc value) {
            this.javaSrc = value;
        }

        /**
         * Gets the value of the lucene property.
         * 
         * @return
         *     possible object is
         *     {@link ProductDTO.SearchIndex.Lucene }
         *     
         */
        public ProductDTO.SearchIndex.Lucene getLucene() {
            return lucene;
        }

        /**
         * Sets the value of the lucene property.
         * 
         * @param value
         *     allowed object is
         *     {@link ProductDTO.SearchIndex.Lucene }
         *     
         */
        public void setLucene(ProductDTO.SearchIndex.Lucene value) {
            this.lucene = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="JavaSrcFsDatabasePath" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="JavaSrcFsDatabaseUrl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "javaSrcFsDatabasePath",
            "javaSrcFsDatabaseUrl"
        })
        public static class JavaSrc {

            @XmlElement(name = "JavaSrcFsDatabasePath", required = true)
            protected String javaSrcFsDatabasePath;
            @XmlElement(name = "JavaSrcFsDatabaseUrl")
            protected String javaSrcFsDatabaseUrl;

            /**
             * Gets the value of the javaSrcFsDatabasePath property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getJavaSrcFsDatabasePath() {
                return javaSrcFsDatabasePath;
            }

            /**
             * Sets the value of the javaSrcFsDatabasePath property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setJavaSrcFsDatabasePath(String value) {
                this.javaSrcFsDatabasePath = value;
            }

            /**
             * Gets the value of the javaSrcFsDatabaseUrl property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getJavaSrcFsDatabaseUrl() {
                return javaSrcFsDatabaseUrl;
            }

            /**
             * Sets the value of the javaSrcFsDatabaseUrl property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setJavaSrcFsDatabaseUrl(String value) {
                this.javaSrcFsDatabaseUrl = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="JavaSrcFsLuceneDatabasePath" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "javaSrcFsLuceneDatabasePath"
        })
        public static class Lucene {

            @XmlElement(name = "JavaSrcFsLuceneDatabasePath", required = true)
            protected String javaSrcFsLuceneDatabasePath;

            /**
             * Gets the value of the javaSrcFsLuceneDatabasePath property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getJavaSrcFsLuceneDatabasePath() {
                return javaSrcFsLuceneDatabasePath;
            }

            /**
             * Sets the value of the javaSrcFsLuceneDatabasePath property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setJavaSrcFsLuceneDatabasePath(String value) {
                this.javaSrcFsLuceneDatabasePath = value;
            }

        }

    }

}
