//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.04 at 06:31:51 PM EDT 
//


package com.slice.datatypes.fileconfiguration;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SearchFileType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SearchFileType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SearchNameText" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SupportedExtensionsList" type="{http://www.slice.com/datatypes/FileConfiguration}string_list"/>
 *       &lt;/sequence>
 *       &lt;attribute name="selectedByDefault" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SearchFileType", propOrder = {
    "searchNameText",
    "supportedExtensionsList"
})
public class SearchFileTypeDTO {

    @XmlElement(name = "SearchNameText", required = true)
    protected String searchNameText;
    @XmlList
    @XmlElement(name = "SupportedExtensionsList", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected List<String> supportedExtensionsList;
    @XmlAttribute(name = "selectedByDefault")
    protected Boolean selectedByDefault;

    /**
     * Gets the value of the searchNameText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchNameText() {
        return searchNameText;
    }

    /**
     * Sets the value of the searchNameText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchNameText(String value) {
        this.searchNameText = value;
    }

    /**
     * Gets the value of the supportedExtensionsList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supportedExtensionsList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupportedExtensionsList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSupportedExtensionsList() {
        if (supportedExtensionsList == null) {
            supportedExtensionsList = new ArrayList<String>();
        }
        return this.supportedExtensionsList;
    }

    /**
     * Gets the value of the selectedByDefault property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSelectedByDefault() {
        return selectedByDefault;
    }

    /**
     * Sets the value of the selectedByDefault property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSelectedByDefault(Boolean value) {
        this.selectedByDefault = value;
    }

}
