//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.22 at 06:13:18 PM EDT 
//


package com.slice.datatypes;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.slice.datatypes package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Query_QNAME = new QName("http://www.slice.com/datatypes", "Query");
    private final static QName _ResourceCreateResponse_QNAME = new QName("http://www.slice.com/datatypes", "ResourceCreateResponse");
    private final static QName _FileContents_QNAME = new QName("http://www.slice.com/datatypes", "FileContents");
    private final static QName _SearchResultList_QNAME = new QName("http://www.slice.com/datatypes", "SearchResultList");
    private final static QName _QueryStatus_QNAME = new QName("http://www.slice.com/datatypes", "QueryStatus");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.slice.datatypes
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SearchResultListDTO }
     * 
     */
    public SearchResultListDTO createSearchResultListDTO() {
        return new SearchResultListDTO();
    }

    /**
     * Create an instance of {@link ResourceCreateResponseDTO }
     * 
     */
    public ResourceCreateResponseDTO createResourceCreateResponseDTO() {
        return new ResourceCreateResponseDTO();
    }

    /**
     * Create an instance of {@link FileContentsDTO }
     * 
     */
    public FileContentsDTO createFileContentsDTO() {
        return new FileContentsDTO();
    }

    /**
     * Create an instance of {@link QueryDTO }
     * 
     */
    public QueryDTO createQueryDTO() {
        return new QueryDTO();
    }

    /**
     * Create an instance of {@link QueryStatusDTO }
     * 
     */
    public QueryStatusDTO createQueryStatusDTO() {
        return new QueryStatusDTO();
    }

    /**
     * Create an instance of {@link ResultEntryDTO }
     * 
     */
    public ResultEntryDTO createResultEntryDTO() {
        return new ResultEntryDTO();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryDTO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.slice.com/datatypes", name = "Query")
    public JAXBElement<QueryDTO> createQuery(QueryDTO value) {
        return new JAXBElement<QueryDTO>(_Query_QNAME, QueryDTO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResourceCreateResponseDTO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.slice.com/datatypes", name = "ResourceCreateResponse")
    public JAXBElement<ResourceCreateResponseDTO> createResourceCreateResponse(ResourceCreateResponseDTO value) {
        return new JAXBElement<ResourceCreateResponseDTO>(_ResourceCreateResponse_QNAME, ResourceCreateResponseDTO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FileContentsDTO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.slice.com/datatypes", name = "FileContents")
    public JAXBElement<FileContentsDTO> createFileContents(FileContentsDTO value) {
        return new JAXBElement<FileContentsDTO>(_FileContents_QNAME, FileContentsDTO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SearchResultListDTO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.slice.com/datatypes", name = "SearchResultList")
    public JAXBElement<SearchResultListDTO> createSearchResultList(SearchResultListDTO value) {
        return new JAXBElement<SearchResultListDTO>(_SearchResultList_QNAME, SearchResultListDTO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryStatusDTO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.slice.com/datatypes", name = "QueryStatus")
    public JAXBElement<QueryStatusDTO> createQueryStatus(QueryStatusDTO value) {
        return new JAXBElement<QueryStatusDTO>(_QueryStatus_QNAME, QueryStatusDTO.class, null, value);
    }

}
