//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.02 at 07:55:37 PM EDT 
//


package com.slice.filenameindexerservice;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.slice.filenameindexerservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FileSearchResultList_QNAME = new QName("http://www.slice.com/FilenameIndexerService", "FileSearchResultList");
    private final static QName _FileSearchResult_QNAME = new QName("http://www.slice.com/FilenameIndexerService", "FileSearchResult");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.slice.filenameindexerservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FileSearchResult }
     * 
     */
    public FileSearchResult createFileSearchResult() {
        return new FileSearchResult();
    }

    /**
     * Create an instance of {@link FileSearchResultList }
     * 
     */
    public FileSearchResultList createFileSearchResultList() {
        return new FileSearchResultList();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FileSearchResultList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.slice.com/FilenameIndexerService", name = "FileSearchResultList")
    public JAXBElement<FileSearchResultList> createFileSearchResultList(FileSearchResultList value) {
        return new JAXBElement<FileSearchResultList>(_FileSearchResultList_QNAME, FileSearchResultList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FileSearchResult }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.slice.com/FilenameIndexerService", name = "FileSearchResult")
    public JAXBElement<FileSearchResult> createFileSearchResult(FileSearchResult value) {
        return new JAXBElement<FileSearchResult>(_FileSearchResult_QNAME, FileSearchResult.class, null, value);
    }

}
