//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.04 at 10:08:59 PM EDT 
//


package com.slice.searchindexdb;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for newQueryIdListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="newQueryIdListType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}long" maxOccurs="unbounded"/>
 *         &lt;element name="FailAfterGivenTimeInMsecs" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "newQueryIdListType", propOrder = {
    "id",
    "failAfterGivenTimeInMsecs"
})
public class NewQueryIdListDTO {

    @XmlElement(name = "Id", type = Long.class)
    protected List<Long> id;
    @XmlElement(name = "FailAfterGivenTimeInMsecs")
    protected Long failAfterGivenTimeInMsecs;

    /**
     * Gets the value of the id property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the id property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Long }
     * 
     * 
     */
    public List<Long> getId() {
        if (id == null) {
            id = new ArrayList<Long>();
        }
        return this.id;
    }

    /**
     * Gets the value of the failAfterGivenTimeInMsecs property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getFailAfterGivenTimeInMsecs() {
        return failAfterGivenTimeInMsecs;
    }

    /**
     * Sets the value of the failAfterGivenTimeInMsecs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setFailAfterGivenTimeInMsecs(Long value) {
        this.failAfterGivenTimeInMsecs = value;
    }

}
